version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: user-api-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - "5523:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: